[build]
  command = "bun install && bun run build"
  publish = ".next"
  base = "submissions/0x4d17d1068f79c7d0"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "cd submissions/0x4d17d1068f79c7d0 && bun run dev"
  port = 3000

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

# Redirects are handled automatically by @netlify/plugin-nextjs

[functions]
  node_bundler = "esbuild"

# Environment variables (set these in Netlify dashboard)
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY
# SUPABASE_SERVICE_ROLE_KEY
# NEXT_PUBLIC_FLOW_NETWORK
# NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
