cast balance --ether --rpc-url https://testnet.evm.nodes.onflow.org 0x1Eba7cC0834d873a2E42F4B502751Bd760605db9


   forge create --broadcast  src/RandomInRange.sol:RandomInRange \
    --rpc-url https://testnet.evm.nodes.onflow.org \
    --private-key 0xe40af275cc5a4b746aa5c143dc474eeedc8b0d99d149bdbdfd6b1fc1160a7e42 \
    --constructor-args 42000000 \
    --legacy


forge create --broadcast src/MyToken.sol:MyToken --rpc-url https://testnet.evm.nodes.onflow.org --private-key 0xe40af275cc5a4b746aa5c143dc474eeedc8b0d99d149bdbdfd6b1fc1160a7e42 --constructor-args 42000000 --legacy


forge create src/RandomInRange.sol:RandomInRange



Deployer: 0x1Eba7cC0834d873a2E42F4B502751Bd760605db9
Deployed to: 0xf8c73bCd64b1c4fB92fB4BDB8A5e74c3ef7C7eDe
Transaction hash: 0x1582da0a2ad1c670d28f7a3b9e9eccc8f5567ae4195098bb1a4abac5b2d338b9
